--- !ruby/object:R2do::State
categories:
  Cat: &82075390 !ruby/object:R2do::Category
    name: Cat
    tasks:
    - !ruby/object:R2do::Task
      description: Task1
      done: false
      date_created: !ruby/object:DateTime 2012-07-25 18:07:16.355986788 +03:00
      date_done: 
    - !ruby/object:R2do::Task
      description: Task2
      done: false
      date_created: !ruby/object:DateTime 2012-07-25 18:07:16.359397420 +03:00
      date_done: 
    - &82092810 !ruby/object:R2do::Task
      description: Task3
      done: false
      date_created: !ruby/object:DateTime 2012-07-25 18:07:16.363530765 +03:00
      date_done: 
    current_task: *82092810
current_category: *82075390
modified: true
